### PR TITLE
Add sifive prci support for SiFive HiFive platform

### PR DESCRIPTION
**Pull request by zongbox**
This driver initializes some necessary PLLs.

### CODE REVIEW

**Review by paul-walmsley-sifive — CHANGES_REQUESTED** [review]
Hi Zong, looks like a good start.  Same comments on this PR as on the freedom-devicetree-tools pull request: the DT compatible string, and the name of the driver, should be Unmatched-specific - so, something like "sifive,unmatched-prci0"

**Comment by zongbox** [comment]
Hi Paul,
The register maps doesn't conflict in unleashed and unmatched, I'd like to distinguish the unleashed and unmatched in this driver, then do different initialization. If it is good to you, I would add the implementation above, and keep this original common name for this prci driver. I wanna do the similar thing for freedom-devicetree-tools.

**Comment by paul-walmsley-sifive** [comment]
> Hi Paul,
> The register maps doesn't conflict in unleashed and unmatched, I'd like to distinguish the unleashed and unmatched in this driver, then do different initialization. If it is good to you, I would add the implementation above, and keep this original common name for this prci driver. I wanna do the similar thing for freedom-devicetree-tools.

Sure, whatever is easiest.  It might be easiest to keep them separate, due to limitations in freedom-devicetree-tools.  Whatever works for you.

My suggestion about "sifive,unmatched-prci0" was rather stupid, as @e-puerto reminded me.  It should be something like "sifive,fu740-c000-prci0" instead.    For that to work, the devicetree-overlay-generator will probably need to be modified to rewrite "sifive,ux00prci0" to "sifive,fu740-c000-prci0" if it sees that the SoC is an Almond (e.g., matching on /compatible = "SiFive,FU740-C000" or whatever)

**Comment by zongbox** [comment]
Changed in v2:
- Use pre-processor directive to separate the implementation for Unleashed and Unmatched by METAL_SIFIVE_FU540_C000_PRCI0 and METAL_SIFIVE_FU740_C000_PRCI0 macro, which are generated by freedom-devicetree-tools.
- The PRCI memory map of Unleashed is subset of Unmatched, so we can use this same driver for them, the freedom-devicetree-tools will generate the different register memory map offsets for them respectively.

**Review by paul-walmsley-sifive — APPROVED** [review]

**Comment by paul-walmsley-sifive** [comment]
Thanks Zong

**Pull request merged**
