### PR TITLE
scrub: do not include a symbol which does not exist

### PR DESCRIPTION
**Pull request by terpstra**
This is breaking downstream repositories

### CODE REVIEW

**Comment by terpstra** [comment]
Or are we supposed to be providing this symbol downstream?

Help needed.

**Comment by terpstra** [comment]
Maybe this should be a weak symbol?

**Comment by knightsifive** [comment]
I believe this symbol is `PROVIDE`-ed here: https://github.com/sifive/ldscript-generator/blob/64d212b6c579da1a5e211fba41de2926ff880069/templates/base.lds#L89 . Personally I don't use this feature.

**Comment by knightsifive** [comment]
... but yeah, should be a weak symbol IMO. Otherwise wouldn't it be undefined when using
https://github.com/sifive/ldscript-generator/blob/64d212b6c579da1a5e211fba41de2926ff880069/templates/scratchpad.lds#L15 ?
@bsousi5

**Comment by bsousi5** [comment]
@terpstra the right way is to fix in the ldscript-generator. Something like this:
diff --git a/templates/base.lds b/templates/base.lds
index f2127ed..35d458b 100644
--- a/templates/base.lds
+++ b/templates/base.lds
@@ -97,6 +97,8 @@ SECTIONS
     PROVIDE( metal_{{ memory.name }}_memory_start = {{ memory.base_hex }} );
     PROVIDE( metal_{{ memory.name }}_memory_end = {{ memory.base_hex }} + {{ memory.length_hex }} );
 {% endfor %}
+{% else %}
+PROVIDE(__metal_eccscrub_bit = {{ default(0) }});
 {% endif %}

How can I reproduce this?
If you need to get pass this, you can add weak symbol in freedom-metal.

**Comment by terpstra** [comment]
It looks like all I needed to do is bump ldscript-generator. Thank you for the pointer.

**Pull request closed without merging**
