### PR TITLE
Remove indirection from metal/machine.h

### PR DESCRIPTION
**Pull request by nategraff-sifive**
Copy the machine header directly into `metal/machine.h` instead of `metal/machine/@MACHINE_NAME@.h`.

### CODE REVIEW

**Comment by sifivekevin** [comment]
I checked out the 'master' branch of freedom-e-sdk, then updated the freedom-metal submodule to this remove-indirection branch.  When I try to create a standalone-project in Freedom Studio I'm getting this error:

```
checking for riscv64-unknown-elf-ar... riscv64-unknown-elf-ar
checking the archiver (riscv64-unknown-elf-ar) interface... ar
checking dependency style of riscv64-unknown-elf-gcc... gcc3
configure: error: in `/c/workspaces/fs-runtime/e31-arty-ri/bsp/build/debug':
configure: error: --with-platform-header is required with the --with-preconfigured option
See `config.log' for more details
make: *** [Makefile:218: /c/workspaces/fs-runtime/e31-arty-ri/bsp/build/debug/Makefile] Error 1
```

**Comment by sifivekevin** [comment]
Switching freedom-metal back to "v201903" restores my ability to create a standalone project.

**Comment by nategraff-sifive** [comment]
@sifivekevin This will only work for the development-19.05 branch, since there are a number of changes throughout E SDK and freedom-devicetree-tools that need to be updated concurrently.

**Comment by nategraff-sifive** [comment]
Does this also fix the problem you're seeing with running `clean`, or does that needs its own fix?

**Comment by sifivekevin** [comment]
That needs a different fix, but that fix lay in Freedom Studio code I believe.  We currently add the ephemeral 'install' folder to the list of folders (it is the only item in the list currently) to examine for headers.    So the index fails after a clean (and also fails when the project is first created, before it get built).   I think we need to add the more permanent folders in the "freedom-metal" tree instead.

**Comment by nategraff-sifive** [comment]
Adding the folders in the freedom-metal tree will fix some of those errors, but `metal/machine.h` and `metal/machine/platform.h` are generated by the freedom-metal build and will only exist in `install/include`, so those two will still have problems.

**Comment by sifivekevin** [comment]
Thinking in the context of a standalone project,  what could a user do to cause either of those files to change in subsequent builds?  In other words, how stable are these headers in a standalone project?

**Comment by sifivekevin** [comment]
Im thinking, is it feasible to make additional copies of these files in folder that does not get removed during a clean, for the sole purpose of maintaining an indexable project.  The freedom-metal makefile can simply replace them as needed.

**Pull request merged**
